name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install zig 0.15.2
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: zig build
        run: zig build -Doptimize=ReleaseSafe

      - name: zig build test
        run: zig build test
